SET(FIND_GTEST_PATHS 
    ${GTEST_ROOT})
    
FIND_PATH(
	GTEST_INCLUDE_DIRS
  NAMES gtest
  PATH_SUFFIXES include
  PATHS ${FIND_GTEST_PATHS}) 

FIND_LIBRARY(
    GTEST_LIBRARY_DEBUG 
    NAMES gtestd
    PATHS ${FIND_GTEST_PATHS}
    PATH_SUFFIXES lib/De
  )
  
FIND_LIBRARY(
    GTEST_LIBRARY_RELEASE 
    NAMES gtest
    PATHS ${FIND_GTEST_PATHS}
    PATH_SUFFIXES lib/Re
  )
  
IF(GTEST_INCLUDE_DIRS AND GTEST_LIBRARY_DEBUG AND GTEST_LIBRARY_RELEASE)
  SET(GTEST_FOUND TRUE)
  SET(GTEST_LIBRARY debug ${GTEST_LIBRARY_DEBUG} optimized ${GTEST_LIBRARY_RELEASE})
ENDIF(GTEST_INCLUDE_DIRS AND GTEST_LIBRARY_DEBUG AND GTEST_LIBRARY_RELEASE)

IF(GTEST_FOUND)
  MESSAGE(STATUS "Found Google Test.")
ENDIF(GTEST_FOUND)