SET(FIND_WWISE_PATHS
    ${WWISE_ROOT}
     /Library/Frameworks
     /usr/local
     /usr
     /sw
     /opt/local
     /opt/csw
     /opt)

#SET(deblinuxlibs "${WWISE_ROOT}/*.a")
SET(libdirs "${WWISE_ROOT}/lib")
#SET(rellinuxlibs "${WWISE_ROOT}/*.a")
#SET(WWISE_LIBRARIES_DEBUG)
FILE(GLOB DEBWINLIBS RELATIVE "${libdirs}/De" "${libdirs}/De/*.lib")
FILE(GLOB RELWINLIBS RELATIVE "${libdirs}/Re" "${libdirs}/Re/*.lib")

FIND_PATH(
	WWISE_INCLUDE_DIRS
  NAMES AK
  PATH_SUFFIXES include
  PATHS ${FIND_WWISE_PATHS})

#Debug
SET(WWISE_LIBRARIES_DEBUG "")
FOREACH(DLIBRARY ${DEBWINLIBS})
  FIND_LIBRARY(
    WWISE_${DLIBRARY}_DEBUG
    NAMES ${DLIBRARY}
    PATHS ${FIND_WWISE_PATHS}
    PATH_SUFFIXES lib/De
  )
  IF(NOT WWISE_${DLIBRARY}_DEBUG)
    MESSAGE(FATAL_ERROR "Could not find Wwise library")
  ENDIF(NOT WWISE_${DLIBRARY}_DEBUG)
  SET(DEBLIB debug ${WWISE_${DLIBRARY}_DEBUG})
  LIST(APPEND WWISE_LIBRARIES_DEBUG debug ${WWISE_${DLIBRARY}_DEBUG})
ENDFOREACH(DLIBRARY ${DEBWINLIBS})

#Release
SET(WWISE_LIBRARIES_RELEASE "")
FOREACH(RLIBRARY ${RELWINLIBS})
  FIND_LIBRARY(
    WWISE_${RLIBRARY}_RELEASE
    NAMES ${RLIBRARY}
    PATHS ${FIND_WWISE_PATHS}
    PATH_SUFFIXES lib/Re
  )
  IF(NOT WWISE_${RLIBRARY}_RELEASE)
    MESSAGE(FATAL_ERROR "Could not find Wwise library")
  ENDIF(NOT WWISE_${RLIBRARY}_RELEASE)
  LIST(APPEND WWISE_LIBRARIES_RELEASE optimized ${WWISE_${RLIBRARY}_RELEASE})
ENDFOREACH(RLIBRARY ${RELWINLIBS})

SET(WWISE_WINDOWS_DEPENDENCIES
"Dsound.lib"
"dxguid.lib"
"ws2_32.lib"
"dinput8.lib"
"Dsound.lib"
"XInput.lib"
"Msacm32.lib"
"Dbghelp.lib"
"d3d9.lib"
"Winmm.lib")

IF (WWISE_INCLUDE_DIRS AND WWISE_LIBRARIES_DEBUG AND WWISE_LIBRARIES_RELEASE)
    SET(WWISE_FOUND TRUE)
    SET(WWISE_LIBRARIES ${WWISE_LIBRARIES_DEBUG} ${WWISE_LIBRARIES_RELEASE})
ENDIF (WWISE_INCLUDE_DIRS AND WWISE_LIBRARIES_DEBUG AND WWISE_LIBRARIES_RELEASE)

IF (WWISE_FOUND)
  MESSAGE(STATUS "Found Wwise.")
ELSE (NOT WWISE_FOUND)
  MESSAGE(FATAL_ERROR "Could not find Wwise library")
ENDIF (WWISE_FOUND)
